name: Build & Release

on:
  push:
    paths:
      - 'source/**'
      - 'premake5.lua'
      - '.github/workflows/build.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build-release:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile-release.yml@workflow
    permissions:
      contents: write
    with:
      PROJECT_NAME: "hcons"
      # required???
      # https://github.com/RaphaelIT7/gmod-common-module-base/blob/2da793e109cb89e20fd3bcc0b6a66f817bf7e8a2/.github/workflows/compile-release.yml#L786-L804
      BUILD_LINUX: "true"
      BUILD_WINDOWS: "false"
      BUILD_64x: "false"
      BUILD_32x: "true"
      ARTIFACT_EXPIRE: "1"
      RELEASE_DRAFT: true
      UPLOAD_PDB: true
      RELEASE_DELETEARTIFACT: true