name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "hcons"
      BUILD_WINDOWS: "false"
      UPLOAD: "artifact"
      # build_64x is "false" by default
      # build_32x is "true" by default
      # realm is "sv" by default