name: Build & Release

on:
  push:
    paths:
      - 'source/**'
      - 'premake5.lua'
      - '.github/workflows/compile-release.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "hcons"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "3"

  release:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: /artifact/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: /artifact/gmsv_hcons_linux.dll
          generate_release_notes: true
          draft: true
          name: ${{ github.run_id }}