name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "hcons"
      # build_64x is "false" by default
      # build_32x is "true" by default
      # realm is "sv" by default
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release (${{ github.ref }})
          body: |
            ${{ github.ref }} release was published using automated action.
          draft: false
          prerelease: true
