name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmodcommon-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "hcons"
      UPLOAD: "artifact"
